app = "nanobot-v2"
primary_region = "iad"

[build]
dockerfile = "dockerfile"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 18790
min_machines_running = 1
processes = ["app"]

[[mounts]]
destination = "/Nano"
source = "nanobot_data"

[processes]
app = "/app/start.sh"

[[vm]]
cpu_kind = "shared"
cpus = 4
memory = "2gb"
memory_mb = 2048